### ISSUE TITLE
I dont understand why people turn off comments tbh

### ISSUE THREAD

**Issue by SHsuperCM** [Darkhax-Minecraft/NoAI-Spawn-Eggs#1]

**Comment by SHsuperCM** [comment]
Anyway, the short description is wrong in curse, It says 
"Adds AI variants with no spawn eggs"
where it should be the opposite..

**Comment by Darkhax** [comment]
You're right, the comments were disabled unintentionally. It's somewhat of a muscle memory issue for me. Either way, thanks for the report, I will fix the description in the moment.
